# Generated by Django 4.2.7 on 2023-11-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
